export const agentMarketAbi = [
  "event TaskCreated(uint256 indexed taskId, address indexed requester, uint256 bounty, uint8 riskTier)",
  "event TaskLocked(uint256 indexed taskId, address indexed provider, bytes32 payloadHash, string payloadCid)",
  "event TaskChallenged(uint256 indexed taskId, address indexed requester, uint256 challengeFee)",
  "event JurorSelectionRequested(uint256 indexed taskId, uint256 requestId)",
  "event JurorSelected(uint256 indexed taskId, address indexed juror)",
  "event JurorSelectionCompleted(uint256 indexed taskId)",
  "event JurorCommitted(uint256 indexed taskId, address indexed juror, bytes32 commitHash)",
  "event JurorRevealed(uint256 indexed taskId, address indexed juror, bool valid)",
  "event TaskSettled(uint256 indexed taskId, bool providerWins)",
  "function createTask(bytes32 taskSchemaHash, uint256 bounty, uint64 ttlSeconds, uint8 riskTier) payable returns (uint256)",
  "function acceptAndSubmit(uint256 taskId, bytes32 payloadHash, string payloadCid) payable",
  "function calculateChallengeFee(uint256 taskId) view returns (uint256)",
  "function challenge(uint256 taskId) payable",
  "function commitVote(uint256 taskId, bytes32 commitHash)",
  "function revealVote(uint256 taskId, bool valid, bytes32 salt)",
  "function finalizeDispute(uint256 taskId)",
  "function settleAfterTTL(uint256 taskId)",
  "function registerJuror() payable",
  "function addJurorStake() payable",
  "function unregisterJuror()",
  "function withdrawJurorStake(uint256 amount)",
  "function setVrfConfig(bytes32 keyHash, uint64 subId, uint16 confirmations, uint32 callbackGasLimit)",
  "function setFeeConfig(uint256 baseBps, uint256 minFee, uint256 maxLossBps)",
  "function setDisputeWindows(uint64 commitSeconds, uint64 revealSeconds)",
  "function setJurorConfig(uint256 minStake, uint256 slashBps, uint64 exitDelaySeconds, uint8 maxTier)",
  "function commitPeriodSeconds() view returns (uint64)",
  "function revealPeriodSeconds() view returns (uint64)"
];
